config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  post 'home/submit'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bubbe.rb
class Bubbe < ApplicationRecord
  has_many :children
end

app/models/child.rb
class Child < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def submit
    bubs = Bubbe.create(name: mishpacha_params[:bubbe_name], email: mishpacha_params[:email])
    mishpacha_params[:children].to_h.each { |_, child_params| bubs.children.create(child_params) }
    FormMailer.new.send_results(bubs).deliver
    render json: {success: true}, status: :ok
  end
  
  private
  def mishpacha_params
    params.require(:bubbe).permit(:bubbe_name, :email, children: {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!--<div class="xl:w-full border-b border-gray-300 dark:border-gray-700 py-5">-->
<!--  <div class="flex items-center w-11/12 mx-auto">-->
<!--    <p class="text-lg text-gray-800 dark:text-gray-100 font-bold">Bubbes & Books</p>-->
<!--  </div>-->
<!--</div>-->
<%= form_with url: home_submit_path, id: 'bubbes-form', scope: :bubbe do |f| %>
  <div class="container mx-auto shadow bg-white dark:bg-gray-800 rounded">
    <div class="md:w-10/12 mx-auto">
      <div class="mx-auto xl:mx-0">
        <div class="bg-center bg-cover bg-no-repeat rounded relative sm:mt-8 h-48 sm:h-72 md:h-96 py-4">
          <%= image_tag 'hero.png', class:"w-full h-full object-cover overflow-hidden rounded shadow" %>
          <div class="w-20 h-20 rounded-full bg-cover bg-center bg-no-repeat absolute bottom-0 -mb-10 ml-12 shadow">
            <%= image_tag 'profilepic.jpg', class: "w-full h-full object-cover overflow-hidden absolute z-0 rounded-full shadow" %>
          </div>
        </div>
        <div class="w-11/12 md:grid md:grid-cols-2 md:gap-4 mx-auto">
          <div class="mt-16 flex flex-col">
            <label for="bubbe_name" class="pb-2 text-sm font-bold text-gray-800 dark:text-gray-100">Name</label>
            <%= f.text_field :bubbe_name, placeholder: 'What should I call you?', class: "border border-gray-300 dark:border-gray-700 pl-3 py-3 shadow-sm rounded text-sm focus:outline-none focus:border-indigo-700 text-gray-800 bg-transparent dark:text-gray-100" %>
          </div>
          <div class="mt-4 md:mt-16 flex flex-col">
            <label for="email" class="pb-2 text-sm font-bold text-gray-800 dark:text-gray-100">Email</label>
            <%= f.text_field :email, placeholder: "youremail@example.com", class: "border border-gray-300 dark:border-gray-700 pl-3 py-3 shadow-sm rounded text-sm focus:outline-none focus:border-indigo-700 bg-transparent resize-none text-gray-800 dark:text-gray-100" %>
          </div>
          <div class="border border-gray-300 p-4 rounded col-span-2 xl:col-auto mt-4 md:mt-auto">
            <div class="flex justify-between">
              <div class="flex flex-col">
                <%= f.label :name, 'Child name', class: 'pb-2 text-sm font-bold text-gray-800 dark:text-gray-100' %>
                <%= f.text_field :name, placeholder: "Enter child's name", id: 'child-name-input', class: "w-48 border border-gray-300 dark:border-gray-700 pl-3 py-3 shadow-sm rounded text-sm focus:outline-none focus:border-indigo-700 bg-transparent resize-none text-gray-800 dark:text-gray-100" %>
              </div>
              <div class="flex flex-col">
                <%= f.label :age, class: 'pb-2 text-sm font-bold text-gray-800' %>
                <div class="w-24 border border-gray-300 dark:border-gray-700 pl-3 py-3 shadow-sm rounded text-sm focus:outline-none focus:border-indigo-700 bg-transparent resize-none text-gray-800 dark:text-gray-100">
                  <%= f.select :age, options_for_select((1..13).to_a), { selected: 1 }, id: 'age-input' %>
                </div>
              </div>
            </div>
            <div class="flex flex-col mt-4">
              <%= f.label :interests, 'Enter Interests', class: "pb-2 text-sm font-bold text-gray-800 dark:text-gray-100 " %>
              <%= f.text_area :interests, id: "interests-input", placeholder: 'Comma Separated. ex: Sports, Dance, Art', class: "border border-gray-300 dark:border-gray-700 pl-3 py-3 shadow-sm rounded text-sm focus:outline-none focus:border-indigo-700 bg-transparent resize-none text-gray-800 dark:text-gray-100" %>
            </div>
            <div class="flex justify-end">
              <a href="javascript: void(0)" class="add-child mx-2 my-2 flex items-center bg-gray-100 transition duration-150 ease-in-out hover:bg-gray-200 rounded border border-gray-300 text-gray-600 pl-3 pr-6 py-2 text-sm">
                <span class="h-4 w-4 mr-2 flex justify-center items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                    <line x1="12" y1="5" x2="12" y2="19"/>
                    <line x1="5" y1="12" x2="19" y2="12"/>
                  </svg>
                </span>
                Add Child
              </a>
            </div>
          </div>
          <div>
            <div class="mt-4 hidden sm:block">
              <div class="">
                <ul class="results text-gray-500 transition"></ul>
              </div>
            </div>
          </div>
          <div class="mt-4 sm:hidden">
            <div class="">
              <ul class="results text-gray-500 transition"></ul>
            </div>
          </div>
          <div class="flex justify-end">
          </div>
          <div class="mt-16 flex flex-col"></div>
        </div>
      </div>
    </div>
    <div class="w-full py-4 sm:px-12 px-4 bg-gray-100 dark:bg-gray-700 mt-6 flex justify-end rounded-bl rounded-br">
      <button id="reset-form" class="btn text-sm focus:outline-none text-gray-600 border border-gray-300 dark:hover:border-gray-500 py-2 px-6 mr-4 rounded hover:bg-gray-200 transition duration-150 ease-in-out">Start Over</button>
      <button class="bg-indigo-700 transition duration-150 ease-in-out hover:bg-indigo-600 rounded text-white px-8 py-2 text-sm focus:outline-none" type="submit">Submit</button>
    </div>

<% end %>


<script type="text/javascript" charset="utf-8">
  $(function () {
    const $form = $('#bubbes-form')
    let childrenCount = 0;
    $('.add-child').on('click', function () {
      const nameInput = $('#child-name-input');
      const ageInput = $('#age-input');
      const interestsInput = $('#interests-input');
      let name = nameInput.val();
      let age = ageInput.val();
      let interests = interestsInput.val();
      if (name.length > 1) {
        childrenCount += 1;
        $('.results').append(`<li> <span class="text-black font-bold"> ${name}</span> <br> <div class="ml-4"> Age: ${age} <br> Interests: ${interests}</div></li>`);
        $form.append(`<input type="hidden" name="bubbe[children[${childrenCount}[name]]]" value="${name}">`);
        $form.append(`<input type="hidden" name="bubbe[children[${childrenCount}[age]]]" value="${age}">`);
        $form.append(`<input type="hidden" name="bubbe[children[${childrenCount}[interests]]]" value="${interests}">`);
        nameInput.val('');
        ageInput.val(1);
        interestsInput.val('');
      }
    })

    $form.on('submit', function(e){
      e.preventDefault();
      $.post($form.attr('action'), $form.serialize()).done(function(response){
        swal('Thank you for your interest!')
      })
    })

    $('#reset-form').on('click', function(e){
      e.preventDefault();
      location.reload();
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BubbesAndBooks</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background-color: #F3F4E4;">


<%= yield %>

</body>
</html>